server:
    port: 8811
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.1.8:3306/order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: zevin@123
        max-wait: 60000
        max-active: 100
        min-idle: 10
        initial-size: 10
mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    typeAliasesPackage: com.zhengwei.rocket
    global-config:
        db-config:
            field-strategy: not-empty
            id-type: auto
            db-type: mysql
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true
        auto-mapping-unknown-column-behavior: none
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
